### ISSUE TITLE
Unstable NVIDIA open source (need a proprietary image?)

### ISSUE THREAD

**Issue by badnetmask** [ublue-os/bazzite-dx#73]
Not sure if this is the right place to report this, so please let me know if you want me to move somewhere else.

I installed Bazzite DX using the `bazzite-dx-gnome-nvidia-open`. It was quite unstable for a few days. I usually keep the laptop on with the screen locked, and at some random point I would not be able to unlock the screen. If I SSH into it (from another laptop) I would see this error:

```
May 05 09:27:44 localhost /usr/bin/nvidia-powerd[1627]: error setting power limit
May 05 09:27:44 localhost /usr/bin/nvidia-powerd[1627]: Error setting GPU limit: 80000.
May 05 09:27:46 localhost /usr/bin/nvidia-powerd[1627]: Failed to get topology status f
May 05 09:27:48 localhost /usr/bin/nvidia-powerd[1627]: Failed to get topology status f
May 05 09:27:50 localhost /usr/bin/nvidia-powerd[1627]: Failed to get topology status f
```

Looking a little further back in the journal, I noticed that the NVIDIA failed a little while after the screen was locked, or went idle:

```
May 05 09:26:06 localhost kernel: NVRM: GPU at PCI:0000:01:00: GPU-10efc657-a646-aaab-d809-9c478fc35a72
May 05 09:26:06 localhost kernel: NVRM: Xid (PCI:0000:01:00): 79, GPU has fallen off the bus.
May 05 09:26:06 localhost kernel: NVRM: GPU 0000:01:00.0: GPU has fallen off the bus.
May 05 09:26:06 localhost kernel: NVRM: kgspRcAndNotifyAllChannels_IMPL: RC all channels for critical error 79.
May 05 09:26:06 localhost kernel: NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!
```

After fighting multiple possible causes, I gave up, and re-based my system using the `bazzite-nvidia` image, and since them there were no more lock ups. It's been stable and faster for 2 days. Even from the statistics, I can see that the video card is using less power, less memory and less GPU cycles.

Basically it seems like there is an issue with the NVIDIA open source drivers, so I have two questions:

a) What more information do you need to debug this problem? The laptop is a 2021 Razer Blade 15 with a `NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q] (rev a1)`. I was running the 42.20250502 DX image, now I'm running the non-DX image 42.20250501.

b) Would you consider creating a DX image with the proprietary drivers?

Thank you.

EDIT: spoke a bit too soon. After 2 days working fine, a little bit after I filed this bug the laptop locked up again, with the same "GPU has fallen off the bus" message.

**Comment by tulilirockz** [comment]
This stuff is concerning but we can't do much about it, `nvidia`'s proprietary driver wont be supported anymore on any new Universal Blue things as nvidia themselves arent going to support their proprietary driver, the best you can do is report the bug you got to the [`nvidia-open` repository](https://github.com/NVIDIA/open-gpu-kernel-modules) and hope for the best

**Comment by Pryka** [comment]
I have a feeling that both @badnetmask and you @tulilirockz are mixing stuff.

There is only proprietary driver from NVIDIA. They just recently opened kernel module, driver blob is still closed as always.

All NVIDIA images use proprietary NVIDIA driver.


@badnetmask
You are on the correct image, it looks like yet another sleep/suspend issue with NVIDIA.

**Comment by tulilirockz** [comment]
Just hid my comment to clear up confusion, basically we just dont want to support the proprietary nvidia kernel module (not the userspace driver, just the kmod) on new images

**Comment by badnetmask** [comment]
Okay, so I'm still confused about the difference between the "open" and the non-open image.

But, for the sake of argument, let's say I switch back to the "open" image: what would be the next steps in this particular bug report? Is it something that can/could be discussed here, or should it be moved elsewhere?

**Comment by Pryka** [comment]
Main Bazzite have two NVIDIA images `nvidia-open` and just `nvidia` both of them use NVIDIA proprietary drivers.

NVIDIA splits its drivers into main driver blob and kernel module. The difference here is the kernel module, one is open source, second one is closed. Both are made by NVIDIA. Open source one is new and it's here to replace old closed one. I think that `bazzite-dx` being a new addition to the family don't even have closed module version, no point in that, it will be killed by NVIDIA relatively soon. 

The main driver part here was and is always proprietary.

To sum up - you are already using latest NVIDIA proprietary drivers with open kernel module. Entirely made by NVIDIA for Linux in recommended by NVIDIA configuration.

As for your issue, I'm not sure if Bazzite can do anything about it. 

---------------------

`nvidia-open` - open kernel module

`nvidia` - closed kernel module

Again, driver is the same, kernel module is different.

**Comment by antheas** [comment]
The dx images will never support the proprietary module. The justification for that is that we need to clean up our tech debt and if you're a dev, using a GPU that requires the proprietary module is sad.

Therefore, dx will always have one Nvidia image, that's `-nvidia` and it corresponds to the open kernel module.

The open and closed modules have different issues each. So maybe the issues of the closed one are better at one particular time. It does not justify our overhead of building those images or your overhead of switching between them. You just have to stick with it and hope Nvidia fixes the bugs

**Comment by badnetmask** [comment]
> Or we fix the bug if we caused it.
@antheas - and what kind of investigation can we do here, in order to figure out where the bug is coming from?

**Comment by antheas** [comment]
Which image works and which doesn't?

**Comment by badnetmask** [comment]
> Which image works and which doesn't?

Neither of them work. Main Bazzite just took longer to crash than DX.

**Comment by antheas** [comment]
Can you look at releases and test a build with a previous kernel?

**Comment by antheas** [comment]
Try the previous version. Just that

**Comment by badnetmask** [comment]
> Try the previous version. Just that

Okay. Initially I tried to rebase into the last 41 release, but apparently there is a bug that prevents that from happening, so instead I just rebased to the first 42 release (downgraded kernel from 6.14.4-103.bazzite.fc42.x86_64 to 6.14.4-103.bazzite.fc42.x86_64). Let's see how this one behaves.

**Comment by badnetmask** [comment]
I think there's some progress.
I've been working on this laptop since yesterday, I even put it to sleep multiple times, and it was working fine.
Today I ran job via Ollama that pegged my GPU for about 4 hours. I completely forgot it was running, and tried to put the laptop to sleep, and that did not work.
Looking at the logs, it seems like it is a bug that has already been reported with GNOME not going into suspend.
So, I don't have time right now, but I will try the GNOME trick another time.
At any rate, it does seem like the older NVIDIA driver has been working more stable than the newer one.

**Comment by badnetmask** [comment]
So yeah, I have been running `42.20250417` for a few days, and it worked fine, until I hit the [Gnome suspend bug](https://github.com/ublue-os/bazzite/issues/2437).
Now I rebased into `42.20250512` (6.14.4-104.bazzite.fc42.x86_64) to see how things go.

**Comment by badnetmask** [comment]
I've been trying different Bazzite images, all of them end up freezing with the same errors after about two days. The latest one I'm using is `42.20250603`.

So now I'm totally unsure if this is a software or hardware problem.

**Comment by xalt7x** [comment]
To my surprise, random freezing completely gone after I switched from GNOME to KDE Plasma image.

> Nvidia proprietary driver is not long for this world and we won't spend any time on it for a developer image.
That's good to know. I've been wondering about the source of this and found kinda confirmation on [NVidia tech blog](https://developer.nvidia.com/blog/nvidia-transitions-fully-towards-open-source-gpu-kernel-modules/):
> At the time, we announced that more robust and fully-featured GeForce and Workstation Linux support would follow in subsequent releases and the NVIDIA Open Kernel Modules would eventually supplant the closed-source driver.

**Comment by badnetmask** [comment]
In case anyone find this bug in the future: the latest driver (575.64.03) made it even more unstable. After a lot of struggle I had the weird idea of disabling "NVIDIA Optimus" in the BIOS itself. The system appears to be a lot more stable now.
